import json, re

with open('assets/questions/tkp.json', encoding='utf-8') as f:
    content = f.read()

# Longest replacements first to avoid partial replacements
replacements = [
    ("индивидуалистическая", "individualistis"),
    ("коллективистическая", "kolektivistik"),
    ("высококвалифицированный", "sangat berkualitas tinggi"),
    ("дисквалифицировать", "mendiskualifikasi"),
    ("непрофессионально", "tidak profesional"),
    ("результативности", "hasil kerja"),
    ("недобросовестный", "tidak beriktikad baik"),
    ("распространения", "penyebaran"),
    ("государственных", "negara"),
    ("организационная", "organisasi"),
    ("образовательные", "pendidikan"),
    ("модифицировать", "memodifikasi"),
    ("информационных", "informasi"),
    ("информационные", "informasi"),
    ("информационная", "informasi"),
    ("дисциплинарная", "disipliner"),
    ("дисциплинарные", "disipliner"),
    ("удовлетворения", "kepuasan"),
    ("могущественный", "berkuasa"),
    ("общественность", "masyarakat luas"),
    ("общественности", "masyarakat luas"),
    ("общественный", "sosial"),
    ("сертифицирован", "tersertifikasi"),
    ("иммиграционном", "imigrasi"),
    ("финансирования", "pembiayaan"),
    ("индивидуальный", "individu"),
    ("справедливость", "keadilan"),
    ("преувеличивают", "membesar-besarkan"),
    ("представители", "perwakilan"),
    ("импрувировать", "meningkatkan"),
    ("финансируется", "dibiayai"),
    ("благоприятный", "menguntungkan"),
    ("неразглашении", "kerahasiaan"),
    ("объективность", "objektivitas"),
    ("категорически", "secara kategoris"),
    ("неофициальный", "tidak resmi"),
    ("категоризация", "kategorisasi"),
    ("благодарность", "ucapan terima kasih"),
    ("нереалистично", "tidak realistis"),
    ("отрицательный", "negatif"),
    ("администрации", "administrasi"),
    ("потенциальный", "potensial"),
    ("сопутствующий", "伴"),
    ("распределении", "distribusi"),
    ("обязательства", "kewajiban"),
    ("преподаватель", "dosen"),
    ("руководитель", "pemimpin"),
    ("конфронтации", "konfrontasi"),
    ("рекомендуйте", "rekomendasikan"),
    ("альтернативы", "alternatif"),
    ("использовать", "menggunakan"),
    ("рекомендации", "rekomendasi"),
    ("доминировать", "mendominasi"),
    ("отслеживание", "pelacakan"),
    ("соответствие", "kesesuaian"),
    ("традиционных", "tradisional"),
    ("безопасность", "keamanan"),
    ("материальная", "material"),
    ("программного", "perangkat lunak"),
    ("коммуникации", "komunikasi"),
    ("существующие", "yang ada"),
    ("существующий", "yang ada"),
    ("повідомлення", "pesan"),
    ("Определенные", "tertentu"),
    ("Исследования", "penelitian"),
    ("политический", "politik"),
    ("опубликовать", "mempublikasikan"),
    ("публиковать", "mempublikasikan"),
    ("публикация", "publikasi"),
    ("публикации", "publikasi"),
    ("Публиковать", "mempublikasikan"),
    ("человеческая", "manusiawi"),
    ("эксплуатации", "pemanfaatan"),
    ("стабильность", "stabilitas"),
    ("справедливый", "adil"),
    ("возможностей", "peluang"),
    ("возможности", "peluang"),
    ("возможность", "peluang"),
    ("одновременно", "secara bersamaan"),
    ("документация", "dokumentasi"),
    ("альтернатива", "pilihan lain"),
    ("единственным", "satu-satunya"),
    ("исследование", "penelitian"),
    ("университете", "universitas"),
    ("коллективная", "kolektif"),
    ("социального", "sosial"),
    ("социальные", "sosial"),
    ("медицинские", "medis"),
    ("медицинская", "medis"),
    ("медицинский", "medis"),
    ("критический", "kritikal"),
    ("приватность", "privasi"),
    ("сотрудников", "karyawan"),
    ("невідповідь", "tidak sesuai"),
    ("операционал", "operasional"),
    ("координатор", "koordinator"),
    ("современная", "modern"),
    ("стандартный", "standar"),
    ("технические", "teknis"),
    ("разработчик", "pengembang"),
    ("обеспечения", "penyediaan"),
    ("внимательно", "dengan teliti"),
    ("руководство", "panduan"),
    ("комапромисс", "kompromi"),
    ("осигуратель", "penjamin"),
    ("последствий", "akibat"),
    ("независимый", "independen"),
    ("коллективно", "secara kolektif"),
    ("компенсации", "kompensasi"),
    ("презентации", "presentasi"),
    ("действующая", "berlaku"),
    ("технический", "teknis"),
    ("юридический", "hukum"),
    ("параллельно", "secara paralel"),
    ("программные", "perangkat lunak"),
    ("организаций", "organisasi"),
    ("адвокатская", "pengacara"),
    ("структурная", "struktural"),
    ("необходимые", "diperlukan"),
    ("манипуляция", "manipulasi"),
    ("манипуляции", "manipulasi"),
    ("последствия", "dampak"),
    ("вовлечение", "keterlibatan"),
    ("иммиграции", "imigrasi"),
    ("иммиграция", "imigrasi"),
    ("дипломатия", "diplomasi"),
    ("интеграции", "integrasi"),
    ("соглашение", "perjanjian"),
    ("полномочий", "kewenangan"),
    ("конкретный", "konkret"),
    ("разработки", "pengembangan"),
    ("требования", "persyaratan"),
    ("количество", "jumlah"),
    ("культурную", "budaya"),
    ("культурная", "budaya"),
    ("независимо", "secara independen"),
    ("информации", "informasi"),
    ("нормальный", "normal"),
    ("незыблемый", "tidak dapat digoyahkan"),
    ("объявляете", "mengumumkan"),
    ("критически", "secara kritikal"),
    ("финансовый", "keuangan"),
    ("финансовые", "keuangan"),
    ("финансовая", "keuangan"),
    ("финансовой", "keuangan"),
    ("финансовых", "keuangan"),
    ("директоров", "direktur"),
    ("объяснение", "penjelasan"),
    ("победителя", "pemenang"),
    ("обращаться", "berkunjung"),
    ("масштабный", "berskala besar"),
    ("показатели", "indikator"),
    ("анонимного", "anonim"),
    ("информацию", "informasi"),
    ("достаточно", "cukup"),
    ("дальнейший", "selanjutnya"),
    ("документов", "dokumen"),
    ("управления", "pengelolaan"),
    ("исключений", "pengecualian"),
    ("специалист", "spesialis"),
    ("накопитель", "penyimpan"),
    ("индивидуум", "individu"),
    ("прозрачный", "transparan"),
    ("нескольких", "beberapa"),
    ("финансовая", "keuangan"),
    ("наблюдение", "pengamatan"),
    ("постоянный", "tetap"),
    ("бесплатные", "gratis"),
    ("переходный", "transisi"),
    ("отчетности", "pelaporan"),
    ("достижения", "pencapaian"),
    ("результаты", "hasil"),
    ("письменный", "tertulis"),
    ("структура", "struktur"),
    ("агентство", "agen"),
    ("признания", "pengakuan"),
    ("обработки", "pemrosesan"),
    ("изменение", "perubahan"),
    ("аллокация", "alokasi"),
    ("тенденция", "tren"),
    ("результат", "hasil"),
    ("параметры", "parameter"),
    ("поддержки", "dukungan"),
    ("системний", "sistem"),
    ("системный", "sistem"),
    ("поддержка", "dukungan"),
    ("транзиции", "transisi"),
    ("учитывать", "memperhitungkan"),
    ("обнаружен", "terungkap"),
    ("директору", "kepada direktur"),
    ("конкреный", "konkret"),
    ("нормально", "normal"),
    ("конкретый", "konkret"),
    ("культурно", "secara budaya"),
    ("категории", "kategori"),
    ("поведения", "perilaku"),
    ("частичную", "parsial"),
    ("аудиторов", "akuntan"),
    ("сохранять", "menyimpan"),
    ("системное", "sistem"),
    ("бухгалтер", "akuntan"),
    ("последний", "terakhir"),
    ("понимаете", "memahami"),
    ("сирования", ""),
    ("некоторые", "beberapa"),
    ("несколько", "beberapa"),
    ("благодаря", "berkat"),
    ("приватный", "pribadi"),
    ("рефлексии", "refleksi"),
    ("гражданам", "warga negara"),
    ("граждане", "warga negara"),
    ("предлагая", "menawarkan"),
    ("небольшой", "kecil"),
    ("ситуацией", "situasi"),
    ("журналист", "jurnalis"),
    ("документы", "dokumen"),
    ("источника", "sumber"),
    ("фальшивый", "palsu"),
    ("экспертов", "ahli"),
    ("аудитория", "audiens"),
    ("потенциал", "potensi"),
    ("контракта", "kontrak"),
    ("документи", "dokumen"),
    ("требуется", "diperlukan"),
    ("следующий", "berikutnya"),
    ("экономика", "ekonomi"),
    ("участвуют", "berpartisipasi"),
    ("серьёзный", "serius"),
    ("персоналу", "kepada staff"),
    ("инновации", "inovasi"),
    ("автономия", "otonomi"),
    ("лекарства", "obat"),
    ("бесплатно", "gratis"),
    ("перевести", "menerjemahkan"),
    ("объясняет", "menjelaskan"),
    ("программы", "program"),
    ("реверсной", "terbalik"),
    ("реверсная", "terbalik"),
    ("нуждается", "membutuhkan"),
    ("суммарная", "total"),
    ("групповой", "kelompok"),
    ("поведение", "perilaku"),
    ("материал", "materi"),
    ("развития", "pengembangan"),
    ("конфликт", "konflik"),
    ("элементы", "unsur"),
    ("институт", "lembaga"),
    ("написано", "ditulis"),
    ("проверка", "pemeriksaan"),
    ("задержки", "keterlambatan"),
    ("будущего", "mendatang"),
    ("публично", "secara terbuka"),
    ("компания", "perusahaan"),
    ("компании", "perusahaan"),
    ("компаний", "perusahaan"),
    ("оператор", "operator"),
    ("работает", "bekerja"),
    ("ситуация", "situasi"),
    ("объектив", "objektif"),
    ("варианты", "pilihan"),
    ("этически", "secara etis"),
    ("максимум", "maksimum"),
    ("сообщает", "melaporkan"),
    ("качества", "kualitas"),
    ("директор", "direktur"),
    ("медицина", "kedokteran"),
    ("средства", "sarana"),
    ("связаные", "terkait"),
    ("проблема", "masalah"),
    ("работник", "pekerja"),
    ("работников", "pekerja"),
    ("прописки", "domisili"),
    ("менеджер", "manajer"),
    ("иерархия", "hierarki"),
    ("среднего", "sedang"),
    ("подобное", "serupa"),
    ("практика", "praktik"),
    ("практики", "praktik"),
    ("критерии", "kriteria"),
    ("политики", "kebijakan"),
    ("понимают", "memahami"),
    ("возможно", "mungkin"),
    ("слежение", "pelacakan"),
    ("рискуете", "berisiko"),
    ("успешной", "berhasil"),
    ("описание", "deskripsi"),
    ("объясняя", "menjelaskan"),
    ("спокойно", "dengan tenang"),
    ("слежения", "pelacakan"),
    ("ресурсов", "sumber daya"),
    ("содержат", "mengandung"),
    ("источник", "sumber"),
    ("политику", "kebijakan"),
    ("проектом", "proyek"),
    ("проблемы", "masalah"),
    ("качество", "kualitas"),
    ("документ", "dokumen"),
    ("развитию", "pengembangan"),
    ("контроль", "kontrol"),
    ("являются", "merupakan"),
    ("скорость", "kecepatan"),
    ("психолог", "psikolog"),
    ("является", "merupakan"),
    ("давления", "tekanan"),
    ("кормилец", "pencari nafkah"),
    ("выписать", "menuliskan resep"),
    ("больница", "rumah sakit"),
    ("больницы", "rumah sakit"),
    ("больнице", "rumah sakit"),
    ("получить", "mendapatkan"),
    ("нечестно", "tidak jujur"),
    ("позициям", "posisi"),
    ("студента", "mahasiswa"),
    ("проекта", "proyek"),
    ("проекте", "di proyek"),
    ("энергия", "energi"),
    ("внешних", "eksternal"),
    ("включая", "termasuk"),
    ("команды", "tim"),
    ("команда", "tim"),
    ("команде", "di tim"),
    ("быстрый", "cepat"),
    ("группах", "kelompok"),
    ("анализа", "analisis"),
    ("процесс", "proses"),
    ("частный", "pribadi"),
    ("частное", "privat"),
    ("вопросы", "pertanyaan"),
    ("рабочая", "kerja"),
    ("рабочей", "kerja"),
    ("прогноз", "proyeksi"),
    ("сложный", "rumit"),
    ("вариант", "pilihan"),
    ("системы", "sistem"),
    ("принята", "diterima"),
    ("события", "kejadian"),
    ("событие", "kejadian"),
    ("пациент", "pasien"),
    ("критики", "kritik"),
    ("квартал", "kuartal"),
    ("обычная", "biasa"),
    ("санкции", "sanksi"),
    ("опытный", "berpengalaman"),
    ("другими", "lain"),
    ("членами", "anggota"),
    ("позиция", "posisi"),
    ("позицию", "posisi"),
    ("надежда", "harapan"),
    ("примеры", "contoh"),
    ("адвокат", "pengacara"),
    ("полезен", "berguna"),
    ("который", "yang"),
    ("которые", "yang"),
    ("степени", "derajat"),
    ("запуска", "peluncuran"),
    ("политик", "politikus"),
    ("создать", "menciptakan"),
    ("интерес", "minat"),
    ("превыше", "di atas"),
    ("Перевод", "terjemahan"),
    ("перевод", "terjemahan"),
    ("визовый", "visa"),
    ("решение", "keputusan"),
    ("принцип", "prinsip"),
    ("профиль", "profil"),
    ("крупная", "besar"),
    ("студент", "mahasiswa"),
    ("деканат", "dekanat"),
    ("клиент", "klien"),
    ("данных", "data"),
    ("журнал", "jurnal"),
    ("метода", "metode"),
    ("только", "hanya"),
    ("служба", "layanan"),
    ("данные", "data"),
    ("должны", "harus"),
    ("анализ", "analisis"),
    ("систем", "sistem"),
    ("ошибка", "kesalahan"),
    ("каждый", "setiap"),
    ("каждой", "setiap"),
    ("низкий", "rendah"),
    ("диалог", "dialog"),
    ("кодекс", "kode etik"),
    ("нового", "baru"),
    ("отдела", "departemen"),
    ("стилей", "gaya"),
    ("можете", "dapat"),
    ("ранены", "luka"),
    ("менять", "mengubah"),
    ("сессия", "sesi"),
    ("надзор", "pengawasan"),
    ("победа", "kemenangan"),
    ("центра", "pusat"),
    ("высшей", "tinggi"),
    ("другие", "lain"),
    ("другим", "lain"),
    ("других", "lain"),
    ("бизнес", "bisnis"),
    ("группа", "kelompok"),
    ("первую", "pertama"),
    ("оценки", "penilaian"),
    ("одного", "satu"),
    ("против", "melawan"),
    ("файлов", "file"),
    ("рисков", "risiko"),
    ("теперь", "sekarang"),
    ("знаете", "tahu"),
    ("успеха", "keberhasilan"),
    ("убытки", "kerugian"),
    ("жертва", "korban"),
    ("правда", "kebenaran"),
    ("услуги", "layanan"),
    ("период", "periode"),
    ("хорошо", "baik"),
    ("помочь", "membantu"),
    ("органы", "organ"),
    ("власти", "pemerintah"),
    ("высшим", "tertinggi"),
    ("однако", "namun"),
    ("начали", "mulai"),
    ("должно", "seharusnya"),
    ("больше", "lebih"),
    ("проект", "proyek"),
    ("работа", "pekerjaan"),
    ("через", "melalui"),
    ("канал", "saluran"),
    ("вилиз，质量ного", "jabatan berkualitas"),
    ("вилиз", "jabatan"),
    ("даже", "bahkan"),
    ("видео", "video"),
    ("Видео", "Video"),
    ("среда", "lingkungan"),
    ("среде", "lingkungan"),
    ("рабочей среде", "lingkungan kerja"),
    ("якобы", "diklaim"),
    ("номер", "nomor"),
    ("ваших", "Anda"),
    ("имеют", "memiliki"),
    ("будет", "akan"),
    ("сайты", "situs"),
    ("бонус", "bonus"),
    ("любую", "apapun"),
    ("очень", "sangat"),
    ("риски", "risiko"),
    ("риску", "risiko"),
    ("риск", "risiko"),
    ("Семья", "Keluarga"),
    ("семья", "keluarga"),
    ("время", "waktu"),
    ("школа", "sekolah"),
    ("отчет", "laporan"),
    ("Совет", "nasihat"),
    ("могут", "dapat"),
    ("тысяч", "ribuan"),
    ("лидер", "pemimpin"),
    ("самый", "paling"),
    ("Также", "juga"),
    ("также", "juga"),
    ("ближе", "lebih dekat"),
    ("имеет", "memiliki"),
    ("может", "dapat"),
    ("всего", "semua"),
    ("право", "hak"),
    ("найти", "mencari"),
    ("работ", "pekerjaan"),
    ("когда", "ketika"),
    ("детей", "anak-anak"),
    ("доход", "pendapatan"),
    ("ущерб", "kerugian"),
    ("тогда", "maka"),
    ("нужно", "perlu"),
    ("будут", "akan"),
    ("этика", "etika"),
    ("здесь", "di sini"),
    ("базы", "basis data"),
    ("хотя", "meskipun"),
    ("быть", "ada"),
    ("бы", ""),
    ("пара", "pasangan"),
    ("если", "jika"),
    ("тоже", "juga"),
    ("один", "satu"),
    ("банк", "bank"),
    ("меры", "tindakan"),
    ("план", "rencana"),
    ("виза", "visa"),
    ("где", "di mana"),
    ("без", "tanpa"),
    ("это", "ini"),
    ("что", "bahwa"),
    ("его", ""),
    ("веб", "web"),
    ("код", "kode"),
    ("еще", "masih"),
    ("ним", ""),
    ("над", "di atas"),
    ("эти", ""),
    ("При", "Pada"),
    ("уже", "sudah"),
    ("вам", "Anda"),
    ("вас", "Anda"),
    ("ваш", "Anda"),
    ("ваша", "Anda"),
    ("суд", "pengadilan"),
    ("них", ""),
    ("не", "tidak"),
    ("до", "sampai"),
    ("от", "dari"),
    ("но", "tetapi"),
    ("Вы", "Anda"),
    ("да", "ya"),
    ("го", ""),
    ("法律", "hukum"),
    ("ã", "a"),
    ("по", "untuk"),
    ("за", "untuk"),
    ("Во", "Di"),
    ("из", "dari"),
    ("член", "anggota"),
    ("дан可能导致", ""),
    ("кажд与合作者", ""),
    ("в一个大公司", ""),
    ("и如果不治疗", ""),
    ("，看起来", ""),
    ("和的关系", ""),
    ("规章制度", ""),
    ("憮政官員", ""),
    ("不一样的", ""),
    ("，让他们", ""),
    (" пер击先", " "),
    ("不耐烦", ""),
    ("倾向于", ""),
    ("如玉许", ""),
    ("奖学金", ""),
    ("，考虑", ""),
    ("不只是", ""),
    ("因为他", ""),
    ("あ法律", ""),
    (" они将", ""),
    ("帮忙", ""),
    ("상당", ""),
    ("仮설", ""),
    ("私下", ""),
    ("底线", ""),
    ("官僚", ""),
    ("де", ""),
    ("学校", ""),
    ("合作", ""),
    ("他们", ""),
    ("发现", ""),
    ("补贴", ""),
    ("他们将", ""),
    (" се狱", ""),
    (" них", ""),
    (" не", " "),
]

count = 0
for old, new in replacements:
    if old in content:
        content = content.replace(old, new)
        count += 1

print(f"Replacements made: {count}")

with open('assets/questions/tkp.json', 'w', encoding='utf-8') as f:
    f.write(content)

# Verify
with open('assets/questions/tkp.json', encoding='utf-8') as f:
    data = json.load(f)

bad = []
for i, q in enumerate(data):
    for field in ['questionText', 'options', 'explanation', 'answer']:
        val = str(q.get(field, ''))
        if re.search(r'[^\x00-\x7F]', val):
            bad.append((i+1, field))

if bad:
    print(f"TKP Paket 1: STILL {len(bad)} fields with non-ASCII")
    # Show unique remaining chars
    chars = set()
    for i, q in enumerate(data):
        for field in ['questionText', 'options', 'explanation', 'answer']:
            val = str(q.get(field, ''))
            found = re.findall(r'[^\x00-\x7F]', val)
            chars.update(found)
    print(f"Remaining unique non-ASCII chars: {sorted(chars)}")
else:
    print("TKP Paket 1: SEMBUH - Semua 45 soal bersih!")
print(f"Total: {len(data)}")
